// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgE2w5q8WtyW880ybDBu1Ij9R23eK6DeE',
    appId: '1:477216940:web:7872e973b86fdb5422df09',
    messagingSenderId: '477216940',
    projectId: 'chatapp-78086',
    authDomain: 'chatapp-78086.firebaseapp.com',
    storageBucket: 'chatapp-78086.appspot.com',
    measurementId: 'G-1C73KPN9B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC814dySIwNKo4pEpvi3R9WsGf1qMxM9Ac',
    appId: '1:477216940:android:38d7ccc7b17b405b22df09',
    messagingSenderId: '477216940',
    projectId: 'chatapp-78086',
    storageBucket: 'chatapp-78086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0DX_RIxQka-PTJQXmI9TzOz9xeFiyeo',
    appId: '1:477216940:ios:5a98e8ea9df2ac7622df09',
    messagingSenderId: '477216940',
    projectId: 'chatapp-78086',
    storageBucket: 'chatapp-78086.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
